version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      - run:
          command: echo "Building weather-app"
          working_directory: weather-app
      - run:
          command: npm --version
          working_directory: weather-app
      - run:
          command: node --version
          working_directory: weather-app

  lint:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: weather-app
      - run:
          command: echo "Linting weather-app"
          working_directory: weather-app
      - run:
          command: npm run lint
          working_directory: weather-app


  build-and-push-docker-image:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Building docker image
          command: docker build -t weather-app .
      - run:
          name: Push docker image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker tag weather-app:latest ravali121/weather-app
            docker push ravali121/weather-app

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - build-and-push-docker-image:
          requires:
            - lint
