apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - image: ravali121/weather-app:latest
          name: weather-app
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: weather-app-config
                  key: port
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-app-secret
                  key: api_key
          ports:
            - name: api
              containerPort: 3000
              protocol: TCP