apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    name: weather-app
spec:
  selector:
    app: weather-app
  type: LoadBalancer
  ports:
    - name: api
      port: 3000
      nodePort: 30000
      protocol: TCP
