apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: weather-app
  labels:
    app: weather-app
spec:
  selector:
    app: weather-app
  type: LoadBalancer
  ports:
    - name: api
      port: 3000
      targetPort: 3000
      protocol: TCP
